import Head from "next/head";

import Editor from "../components/Editor";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tiptap Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <h1 className="text-5xl font-extrabold mt-24 mb-12">
          Welcome to Tiptap Editor!
        </h1>

        <Editor />
      </main>
    </>
  );
}
